version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: furia_fan_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: furia_fan
      MYSQL_USER: furia
      MYSQL_PASSWORD: furia123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "furia", "-pfuria123"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
